export const POPULAR_CITIES = [
    'Mumbai, Maharashtra',
    'Delhi, Delhi',
    'Bangalore, Karnataka',
    'Hyderabad, Telangana',
    'Ahmedabad, Gujarat',
    'Chennai, Tamil Nadu',
    'Kolkata, West Bengal',
    'Pune, Maharashtra',
    'Jaipur, Rajasthan',
    'Surat, Gujarat',
    'Lucknow, Uttar Pradesh',
    'Kanpur, Uttar Pradesh',
    'Nagpur, Maharashtra',
    'Indore, Madhya Pradesh',
    'Thane, Maharashtra',
    'Bhopal, Madhya Pradesh',
    'Visakhapatnam, Andhra Pradesh',
    'Pimpri-Chinchwad, Maharashtra',
    'Patna, Bihar',
    'Vadodara, Gujarat',
    'Ghaziabad, Uttar Pradesh',
    'Ludhiana, Punjab',
    'Agra, Uttar Pradesh',
    'Nashik, Maharashtra',
    'Faridabad, Haryana',
    'Meerut, Uttar Pradesh',
    'Rajkot, Gujarat',
    'Kalyan-Dombivli, Maharashtra',
    'Vasai-Virar, Maharashtra',
    'Varanasi, Uttar Pradesh',
    'Srinagar, Jammu and Kashmir',
    'Aurangabad, Maharashtra',
    'Dhanbad, Jharkhand',
    'Amritsar, Punjab',
    'Navi Mumbai, Maharashtra',
    'Allahabad, Uttar Pradesh',
    'Ranchi, Jharkhand',
    'Howrah, West Bengal',
    'Coimbatore, Tamil Nadu',
    'Jabalpur, Madhya Pradesh',
    'Gwalior, Madhya Pradesh',
    'Vijayawada, Andhra Pradesh',
    'Jodhpur, Rajasthan',
    'Madurai, Tamil Nadu',
    'Raipur, Chhattisgarh',
    'Kota, Rajasthan',
    'Guwahati, Assam',
    'Chandigarh, Chandigarh',
    'Solapur, Maharashtra',
    'Hubballi-Dharwad, Karnataka',
    'Mysore, Karnataka',
    'Tiruchirappalli, Tamil Nadu',
    'Bareilly, Uttar Pradesh',
    'Aligarh, Uttar Pradesh',
    'Tiruppur, Tamil Nadu',
    'Gurgaon, Haryana',
    'Moradabad, Uttar Pradesh',
    'Jalandhar, Punjab',
    'Bhubaneswar, Odisha',
    'Salem, Tamil Nadu',
    'Warangal, Telangana',
    'Mira-Bhayandar, Maharashtra',
    'Jalgaon, Maharashtra',
    'Guntur, Andhra Pradesh',
    'Thiruvananthapuram, Kerala',
    'Bhiwandi, Maharashtra',
    'Saharanpur, Uttar Pradesh',
    'Gorakhpur, Uttar Pradesh',
    'Bikaner, Rajasthan',
    'Amravati, Maharashtra',
    'Noida, Uttar Pradesh',
    'Jamshedpur, Jharkhand',
    'Bhilai, Chhattisgarh',
    'Cuttack, Odisha',
    'Firozabad, Uttar Pradesh',
    'Kochi, Kerala',
    'Nellore, Andhra Pradesh',
    'Bhavnagar, Gujarat',
    'Dehradun, Uttarakhand',
    'Durgapur, West Bengal',
    'Asansol, West Bengal',
    'Rourkela, Odisha',
    'Nanded, Maharashtra',
    'Kolhapur, Maharashtra',
    'Ajmer, Rajasthan',
    'Akola, Maharashtra',
    'Gulbarga, Karnataka',
    'Jamnagar, Gujarat',
    'Ujjain, Madhya Pradesh',
    'Loni, Uttar Pradesh',
    'Siliguri, West Bengal',
    'Jhansi, Uttar Pradesh',
    'Ulhasnagar, Maharashtra',
    'Jammu, Jammu and Kashmir',
    'Sangli-Miraj & Kupwad, Maharashtra',
    'Mangalore, Karnataka',
    'Erode, Tamil Nadu',
    'Belgaum, Karnataka',
    'Ambattur, Tamil Nadu',
    'Tirunelveli, Tamil Nadu',
    'Malegaon, Maharashtra',
    'Gaya, Bihar',
    'Jalna, Maharashtra',
    'Udaipur, Rajasthan',
    'Maheshtala, West Bengal',
    'Davanagere, Karnataka',
    'Kozhikode, Kerala',
    'Kurnool, Andhra Pradesh',
    'Rajpur Sonarpur, West Bengal',
    'Rajahmundry, Andhra Pradesh',
    'Bokaro, Jharkhand',
    'South Dumdum, West Bengal',
    'Bellary, Karnataka',
    'Patiala, Punjab',
    'Gopalpur, West Bengal',
    'Agartala, Tripura',
    'Bhagalpur, Bihar',
    'Muzaffarnagar, Uttar Pradesh',
    'Bhatpara, West Bengal',
    'Panihati, West Bengal',
    'Latur, Maharashtra',
    'Dhule, Maharashtra',
    'Tirupati, Andhra Pradesh',
    'Rohtak, Haryana',
    'Korba, Chhattisgarh',
    'Bhilwara, Rajasthan',
    'Berhampur, Odisha',
    'Muzaffarpur, Bihar',
    'Ahmednagar, Maharashtra',
    'Mathura, Uttar Pradesh',
    'Kollam, Kerala',
    'Avadi, Tamil Nadu',
    'Kadapa, Andhra Pradesh',
    'Kamarhati, West Bengal',
    'Sambalpur, Odisha',
    'Bilaspur, Chhattisgarh',
    'Shahjahanpur, Uttar Pradesh',
    'Satara, Maharashtra',
    'Bijapur, Karnataka',
    'Rampur, Uttar Pradesh',
    'Shivamogga, Karnataka',
    'Chandrapur, Maharashtra',
    'Junagadh, Gujarat',
    'Thrissur, Kerala',
    'Alwar, Rajasthan',
    'Bardhaman, West Bengal',
    'Kulti, West Bengal',
    'Nizamabad, Telangana',
    'Parbhani, Maharashtra',
    'Tumkur, Karnataka',
    'Khammam, Telangana',
    'Ozhukarai, Puducherry',
    'Bihar Sharif, Bihar',
    'Panipat, Haryana',
    'Darbhanga, Bihar',
    'Bally, West Bengal',
    'Aizawl, Mizoram',
    'Dewas, Madhya Pradesh',
    'Ichalkaranji, Maharashtra',
    'Karnal, Haryana',
    'Bathinda, Punjab',
    'Jalna, Maharashtra',
    'Eluru, Andhra Pradesh',
    'Barasat, West Bengal',
    'Kirari Suleman Nagar, Delhi',
    'Purnia, Bihar',
    'Satna, Madhya Pradesh',
    'Mau, Uttar Pradesh',
    'Sonipat, Haryana',
    'Farrukhabad, Uttar Pradesh',
    'Sagar, Madhya Pradesh',
    'Rourkela, Odisha',
    'Durg, Chhattisgarh',
    'Imphal, Manipur',
    'Ratlam, Madhya Pradesh',
    'Hapur, Uttar Pradesh',
    'Arrah, Bihar',
    'Anantapur, Andhra Pradesh',
    'Karimnagar, Telangana',
    'Etawah, Uttar Pradesh',
    'Ambarnath, Maharashtra',
    'North Dumdum, West Bengal',
    'Bharatpur, Rajasthan',
    'Begusarai, Bihar',
    'New Delhi, Delhi',
    'Gandhidham, Gujarat',
    'Baranagar, West Bengal',
    'Tiruvottiyur, Tamil Nadu',
    'Pondicherry, Puducherry',
    'Sikar, Rajasthan',
    'Thoothukudi, Tamil Nadu',
    'Rewa, Madhya Pradesh',
    'Mirzapur, Uttar Pradesh',
    'Raichur, Karnataka',
    'Pali, Rajasthan',
    'Ramagundam, Telangana',
    'Silchar, Assam',
    'Haridwar, Uttarakhand',
    'Vijayanagaram, Andhra Pradesh',
    'Tenali, Andhra Pradesh',
    'Nagercoil, Tamil Nadu',
    'Sri Ganganagar, Rajasthan',
    'Karawal Nagar, Delhi',
    'Mango, Jharkhand',
    'Thanjavur, Tamil Nadu',
    'Bulandshahr, Uttar Pradesh',
    'Uluberia, West Bengal',
    'Katni, Madhya Pradesh',
    'Sambhal, Uttar Pradesh',
    'Singrauli, Madhya Pradesh',
    'Nadiad, Gujarat',
    'Secunderabad, Telangana',
    'Naihati, West Bengal',
    'Yamunanagar, Haryana',
    'Bidhan Nagar, West Bengal',
    'Pallavaram, Tamil Nadu',
    'Bidar, Karnataka',
    'Munger, Bihar',
    'Panchkula, Haryana',
    'Burhanpur, Madhya Pradesh',
    'Raukela, Odisha',
    'Kharagpur, West Bengal',
    'Dindigul, Tamil Nadu',
    'Gandhinagar, Gujarat',
    'Hospet, Karnataka',
    'Nangloi Jat, Delhi',
    'Malda, West Bengal',
    'Ongole, Andhra Pradesh',
    'Deoghar, Jharkhand',
    'Chapra, Bihar',
    'Haldia, West Bengal',
    'Khandwa, Madhya Pradesh',
    'Nandyal, Andhra Pradesh',
    'Morena, Madhya Pradesh',
    'Amroha, Uttar Pradesh',
    'Anand, Gujarat',
    'Bhind, Madhya Pradesh',
    'Bhalswa Jahangir Pur, Delhi',
    'Madhyamgram, West Bengal',
    'Bhiwani, Haryana',
    'Berhampore, West Bengal',
    'Ambala, Haryana',
    'Morbi, Gujarat',
    'Fatehpur, Uttar Pradesh',
    'Raebareli, Uttar Pradesh',
    'Khora, Uttar Pradesh',
    'Chittoor, Andhra Pradesh',
    'Bhusawal, Maharashtra',
    'Orai, Uttar Pradesh',
    'Bahraich, Uttar Pradesh',
    'Phusro, Jharkhand',
    'Vellore, Tamil Nadu',
    'Mehsana, Gujarat',
    'Raiganj, West Bengal',
    'Sirsa, Haryana',
    'Danapur, Bihar',
    'Serampore, West Bengal',
    'Sultan Pur Majra, Delhi',
    'Guna, Madhya Pradesh',
    'Jaunpur, Uttar Pradesh',
    'Panvel, Maharashtra',
    'Shivpuri, Madhya Pradesh',
    'Surendranagar Dudhrej, Gujarat',
    'Unnao, Uttar Pradesh',
    'Chinsurah, West Bengal',
    'Alappuzha, Kerala',
    'Kottayam, Kerala',
    'Machilipatnam, Andhra Pradesh',
    'Shimla, Himachal Pradesh',
    'Adoni, Andhra Pradesh',
    'Udupi, Karnataka',
    'Katihar, Bihar',
    'Proddatur, Andhra Pradesh',
    'Mahbubnagar, Telangana',
    'Saharsa, Bihar',
    'Dibrugarh, Assam',
    'Jorhat, Assam',
    'Hazaribagh, Jharkhand',
    'Hindupur, Andhra Pradesh',
    'Nagaon, Assam',
    'Sasaram, Bihar',
    'Hajipur, Bihar',
];
